# Generated by Django 5.0.6 on 2024-07-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=10)),
                ('item_name', models.CharField(max_length=50)),
                ('item_categ', models.CharField(max_length=50)),
                ('store', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('per', models.CharField(max_length=50)),
                ('item_img', models.ImageField(upload_to='')),
                ('map_img', models.ImageField(upload_to='')),
            ],
        ),
    ]
