# Generated by Django 5.0.6 on 2024-07-03 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_account_alter_market_map_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='admin_id',
            new_name='admin_username',
        ),
    ]
